name: irisxarray
channels:
        - conda-forge
dependencies:
        - python==3.10.4
        - dask=2022.4.0
        - distributed=2022.4.0
        - iris=3.2.1
        - xarray=2022.3.0
        - bottleneck=1.3.4
        - s3fs=2022.3.0
        - h5py=3.6.0
        - zarr=2.11.3
        - kerchunk=0.0.6
        - pip=22.0.4
        - pip:
            - git+https://github.com/gjoseph92/dask-worker-pools@main
